/* The following code was generated by JFlex 1.6.1 */

package net.sf.joost.grammar;

import net.sf.joost.grammar.cup.Symbol;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>src/main/resources/net/sf/joost/grammar/Yylex</tt>
 */
public class Yylex implements Sym, net.sf.joost.grammar.cup.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int CMT = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\12\0\1\6\1\6\1\6\1\6\22\0\1\36\1\25\1\50\1\0"+
    "\1\14\2\0\1\51\1\3\1\5\1\16\1\17\1\21\1\20\1\15"+
    "\1\10\12\2\1\4\1\0\1\23\1\22\1\24\1\0\1\13\4\1"+
    "\1\47\25\1\1\11\1\0\1\12\1\0\1\1\1\0\1\33\1\1"+
    "\1\42\1\26\1\40\1\1\1\45\1\1\1\27\3\1\1\31\1\34"+
    "\1\32\1\43\1\1\1\35\1\44\1\37\1\46\1\30\1\1\1\41"+
    "\2\1\1\0\1\7\10\0\1\6\u1fa2\0\1\6\1\6\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\1\5\2\1\25"+
    "\3\2\2\1\3\25\1\0\1\3\1\0\1\26\1\27"+
    "\1\30\1\31\1\32\1\33\1\34\2\2\1\35\6\2"+
    "\1\0\1\36\1\0\1\37\1\40\1\3\1\0\1\41"+
    "\1\42\1\43\12\2\2\0\3\2\1\44\1\45\1\0"+
    "\2\2\1\46\2\2\1\0\1\2\1\47\16\2\1\50";

  private static int [] zzUnpackAction() {
    int [] result = new int[107];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\52\0\124\0\176\0\250\0\322\0\374\0\124"+
    "\0\124\0\u0126\0\124\0\124\0\124\0\124\0\u0150\0\124"+
    "\0\124\0\124\0\124\0\124\0\u017a\0\u01a4\0\u01ce\0\u01f8"+
    "\0\u0222\0\u024c\0\u0276\0\u02a0\0\u02ca\0\u02f4\0\u031e\0\u0348"+
    "\0\u0372\0\u039c\0\124\0\322\0\u03c6\0\u03f0\0\u041a\0\u0444"+
    "\0\124\0\124\0\124\0\124\0\124\0\124\0\124\0\u046e"+
    "\0\u0498\0\176\0\u04c2\0\u04ec\0\u0516\0\u0540\0\u056a\0\u0594"+
    "\0\u0372\0\124\0\u039c\0\124\0\u05be\0\u05e8\0\u05e8\0\176"+
    "\0\176\0\176\0\u0612\0\u063c\0\u0666\0\u0690\0\u06ba\0\u06e4"+
    "\0\u070e\0\u0738\0\u0762\0\u078c\0\u07b6\0\u07e0\0\u080a\0\u0834"+
    "\0\u085e\0\124\0\124\0\u0888\0\u08b2\0\u08dc\0\124\0\u0906"+
    "\0\u0930\0\u095a\0\u0984\0\124\0\u09ae\0\u09d8\0\u0a02\0\u0a2c"+
    "\0\u0a56\0\u0a80\0\u0aaa\0\u0ad4\0\u0afe\0\u0b28\0\u0b52\0\u0b7c"+
    "\0\u0ba6\0\u0bd0\0\124";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[107];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\6\1\7\1\10\1\0\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\27\1\30\2\4"+
    "\1\31\1\32\1\33\1\34\1\4\1\35\1\36\2\4"+
    "\1\37\1\40\4\4\1\41\1\42\3\43\1\44\1\45"+
    "\1\43\1\0\43\43\53\0\2\4\1\0\1\46\10\0"+
    "\1\4\2\0\1\4\5\0\10\4\1\0\11\4\4\0"+
    "\1\5\12\0\1\47\22\0\1\50\6\0\1\50\6\0"+
    "\1\51\52\0\1\52\54\0\1\53\43\0\1\47\12\0"+
    "\1\54\56\0\1\55\51\0\1\56\51\0\1\57\30\0"+
    "\2\4\1\0\1\46\10\0\1\4\2\0\1\4\5\0"+
    "\1\4\1\60\6\4\1\0\11\4\3\0\2\4\1\0"+
    "\1\46\10\0\1\4\2\0\1\4\5\0\4\4\1\61"+
    "\3\4\1\0\11\4\3\0\2\4\1\0\1\46\10\0"+
    "\1\4\2\0\1\4\5\0\7\4\1\62\1\0\11\4"+
    "\3\0\2\4\1\0\1\46\10\0\1\4\2\0\1\4"+
    "\5\0\6\4\1\63\1\4\1\0\11\4\3\0\2\4"+
    "\1\0\1\46\10\0\1\4\2\0\1\4\5\0\4\4"+
    "\1\64\3\4\1\0\11\4\40\0\1\35\14\0\2\4"+
    "\1\0\1\46\10\0\1\4\2\0\1\4\5\0\10\4"+
    "\1\0\1\4\1\65\7\4\3\0\2\4\1\0\1\46"+
    "\10\0\1\4\2\0\1\4\5\0\1\66\3\4\1\67"+
    "\3\4\1\0\11\4\3\0\2\4\1\0\1\46\10\0"+
    "\1\4\2\0\1\4\5\0\7\4\1\70\1\0\11\4"+
    "\2\0\50\71\1\72\1\71\51\73\1\72\5\0\1\74"+
    "\45\0\1\75\24\0\10\75\1\0\11\75\4\0\1\47"+
    "\35\0\1\50\6\0\1\50\4\0\1\76\14\0\2\77"+
    "\32\0\2\4\1\0\1\46\10\0\1\4\2\0\1\4"+
    "\5\0\2\4\1\100\5\4\1\0\11\4\3\0\2\4"+
    "\1\0\1\46\10\0\1\4\2\0\1\4\5\0\1\101"+
    "\7\4\1\0\11\4\3\0\2\4\1\0\1\46\10\0"+
    "\1\4\2\0\1\4\5\0\1\102\7\4\1\0\11\4"+
    "\3\0\2\4\1\0\1\46\10\0\1\4\2\0\1\4"+
    "\5\0\1\103\7\4\1\0\11\4\3\0\2\4\1\0"+
    "\1\46\10\0\1\4\2\0\1\4\5\0\10\4\1\0"+
    "\2\4\1\104\6\4\3\0\2\4\1\0\1\46\10\0"+
    "\1\4\2\0\1\4\5\0\5\4\1\105\2\4\1\0"+
    "\11\4\3\0\2\4\1\0\1\46\10\0\1\4\2\0"+
    "\1\4\5\0\3\4\1\106\4\4\1\0\11\4\3\0"+
    "\2\4\1\0\1\46\10\0\1\4\2\0\1\4\5\0"+
    "\4\4\1\107\3\4\1\0\11\4\3\0\2\75\12\0"+
    "\1\75\2\0\1\75\5\0\10\75\1\0\11\75\4\0"+
    "\1\76\50\0\2\4\1\0\1\46\10\0\1\4\2\0"+
    "\1\4\5\0\10\4\1\0\1\4\1\110\7\4\3\0"+
    "\2\4\1\0\1\46\10\0\1\4\2\0\1\4\5\0"+
    "\10\4\1\0\1\111\10\4\3\0\2\4\1\0\1\46"+
    "\10\0\1\4\2\0\1\4\5\0\10\4\1\0\1\112"+
    "\10\4\3\0\2\4\1\0\1\46\10\0\1\4\2\0"+
    "\1\4\5\0\3\4\1\113\4\4\1\0\11\4\3\0"+
    "\2\4\1\0\1\46\10\0\1\4\2\0\1\4\5\0"+
    "\10\4\1\0\3\4\1\114\5\4\3\0\2\4\1\115"+
    "\1\46\10\0\1\4\2\0\1\4\5\0\10\4\1\0"+
    "\11\4\3\0\2\4\1\116\1\46\10\0\1\4\2\0"+
    "\1\4\5\0\10\4\1\0\11\4\3\0\2\4\1\0"+
    "\1\46\10\0\1\4\2\0\1\4\5\0\5\4\1\117"+
    "\2\4\1\0\11\4\3\0\2\4\1\0\1\46\10\0"+
    "\1\4\2\0\1\4\5\0\10\4\1\0\1\4\1\120"+
    "\7\4\3\0\2\4\1\0\1\46\10\0\1\4\2\0"+
    "\1\4\5\0\10\4\1\0\1\4\1\121\7\4\7\0"+
    "\1\122\51\0\1\123\45\0\2\4\1\124\1\46\10\0"+
    "\1\4\2\0\1\4\5\0\10\4\1\0\11\4\3\0"+
    "\2\4\1\0\1\46\10\0\1\4\2\0\1\4\5\0"+
    "\6\4\1\125\1\4\1\0\11\4\3\0\2\4\1\0"+
    "\1\46\10\0\1\4\2\0\1\4\5\0\10\4\1\0"+
    "\5\4\1\126\3\4\7\0\1\127\45\0\2\4\1\0"+
    "\1\46\10\0\1\4\2\0\1\4\5\0\10\4\1\0"+
    "\1\130\10\4\3\0\2\4\1\0\1\46\10\0\1\4"+
    "\2\0\1\4\5\0\10\4\1\0\5\4\1\131\3\4"+
    "\3\0\2\4\1\132\1\46\10\0\1\4\2\0\1\4"+
    "\5\0\10\4\1\0\11\4\3\0\2\4\1\0\1\46"+
    "\10\0\1\4\2\0\1\4\5\0\1\4\1\133\6\4"+
    "\1\0\11\4\7\0\1\134\45\0\2\4\1\0\1\46"+
    "\10\0\1\4\2\0\1\4\5\0\6\4\1\135\1\4"+
    "\1\0\11\4\3\0\2\4\1\0\1\46\10\0\1\4"+
    "\2\0\1\4\5\0\10\4\1\0\6\4\1\136\2\4"+
    "\3\0\2\4\1\0\1\46\10\0\1\4\2\0\1\137"+
    "\5\0\10\4\1\0\11\4\3\0\2\4\1\0\1\46"+
    "\10\0\1\4\2\0\1\4\5\0\1\4\1\140\6\4"+
    "\1\0\11\4\3\0\2\4\1\0\1\46\10\0\1\4"+
    "\2\0\1\4\5\0\6\4\1\141\1\4\1\0\11\4"+
    "\3\0\2\4\1\0\1\46\10\0\1\4\2\0\1\4"+
    "\5\0\10\4\1\0\5\4\1\142\3\4\3\0\2\4"+
    "\1\0\1\46\10\0\1\4\2\0\1\4\5\0\10\4"+
    "\1\0\1\143\10\4\3\0\2\4\1\0\1\46\10\0"+
    "\1\4\2\0\1\4\5\0\7\4\1\144\1\0\11\4"+
    "\3\0\2\4\1\0\1\46\10\0\1\4\2\0\1\4"+
    "\5\0\10\4\1\0\7\4\1\145\1\4\3\0\2\4"+
    "\1\0\1\46\10\0\1\4\2\0\1\4\5\0\10\4"+
    "\1\0\3\4\1\146\5\4\3\0\2\4\1\0\1\46"+
    "\10\0\1\4\2\0\1\4\5\0\10\4\1\0\1\147"+
    "\10\4\3\0\2\4\1\0\1\46\10\0\1\4\2\0"+
    "\1\4\5\0\1\4\1\150\6\4\1\0\11\4\3\0"+
    "\2\4\1\0\1\46\10\0\1\4\2\0\1\4\5\0"+
    "\4\4\1\151\3\4\1\0\11\4\3\0\2\4\1\0"+
    "\1\46\10\0\1\4\2\0\1\4\5\0\6\4\1\152"+
    "\1\4\1\0\11\4\3\0\2\4\1\153\1\46\10\0"+
    "\1\4\2\0\1\4\5\0\10\4\1\0\11\4\2\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3066];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\4\1\2\11\1\1\4\11\1\1\5\11"+
    "\16\1\1\11\2\1\1\0\1\1\1\0\7\11\11\1"+
    "\1\0\1\11\1\0\1\11\2\1\1\0\15\1\2\0"+
    "\3\1\2\11\1\0\2\1\1\11\2\1\1\0\1\1"+
    "\1\11\16\1\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[107];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
public Symbol last = null;
public int withinComment = 0;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Yylex(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 170) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
          {    return new Symbol(EOF);
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { last = new Symbol(error,yychar,yychar+1,yytext()); 
   return last;
            }
          case 41: break;
          case 2: 
            { last = new Symbol(NCNAME,yychar,yychar+yytext().length(),yytext()); 
   return last;
            }
          case 42: break;
          case 3: 
            { last = new Symbol(NUMBER,yychar,yychar+yytext().length(),
                     new Double(yytext())); 
   return last;
            }
          case 43: break;
          case 4: 
            { last = new Symbol(LPAR,yychar,yychar+1,yytext()); 
                    return last;
            }
          case 44: break;
          case 5: 
            { last = new Symbol(COLON,yychar,yychar+1,yytext()); 
                    return last;
            }
          case 45: break;
          case 6: 
            { last = new Symbol(RPAR,yychar,yychar+1,yytext()); 
                    return last;
            }
          case 46: break;
          case 7: 
            { last = new Symbol(BAR,yychar,yychar+1,yytext()); 
                    return last;
            }
          case 47: break;
          case 8: 
            { last = new Symbol(SLASH,yychar,yychar+1,yytext()); 
                    return last;
            }
          case 48: break;
          case 9: 
            { last = new
                    Symbol(LBRACK,yychar,yychar+1,yytext()); 
                    return last;
            }
          case 49: break;
          case 10: 
            { last = new
                    Symbol(RBRACK,yychar,yychar+1,yytext()); 
                    return last;
            }
          case 50: break;
          case 11: 
            { last = new Symbol(AT,yychar,yychar+1,yytext()); 
                    return last;
            }
          case 51: break;
          case 12: 
            { last = new Symbol(DOLLAR,yychar,yychar+1,yytext()); 
                    return last;
            }
          case 52: break;
          case 13: 
            { last = new Symbol(DOT,yychar,yychar+1,yytext()); 
                    return last;
            }
          case 53: break;
          case 14: 
            { last = new Symbol(STAR,yychar,yychar+1,yytext()); 
                    return last;
            }
          case 54: break;
          case 15: 
            { last = new Symbol(PLUS,yychar,yychar+1,yytext()); 
                    return last;
            }
          case 55: break;
          case 16: 
            { last = new Symbol(MINUS,yychar,yychar+1,yytext()); 
                    return last;
            }
          case 56: break;
          case 17: 
            { last = new Symbol(COMMA,yychar,yychar+1,yytext()); 
                    return last;
            }
          case 57: break;
          case 18: 
            { last = new Symbol(EQ,yychar,yychar+1,yytext()); 
                    return last;
            }
          case 58: break;
          case 19: 
            { last = new Symbol(LT,yychar,yychar+1,yytext()); 
                    return last;
            }
          case 59: break;
          case 20: 
            { last = new Symbol(GT,yychar,yychar+1,yytext()); 
                    return last;
            }
          case 60: break;
          case 21: 
            { 
            }
          case 61: break;
          case 22: 
            { yybegin(CMT); withinComment++;
            }
          case 62: break;
          case 23: 
            { last = new Symbol(error,yychar,yychar+1,yytext()); 
                    return last;
            }
          case 63: break;
          case 24: 
            { last = new
                    Symbol(DSLASH,yychar,yychar+2,yytext()); 
                    return last;
            }
          case 64: break;
          case 25: 
            { last = new Symbol(DDOT,yychar,yychar+1,yytext()); 
                    return last;
            }
          case 65: break;
          case 26: 
            { last = new Symbol(LE,yychar,yychar+2,yytext()); 
                    return last;
            }
          case 66: break;
          case 27: 
            { last = new Symbol(GE,yychar,yychar+2,yytext()); 
                    return last;
            }
          case 67: break;
          case 28: 
            { last = new Symbol(NE,yychar,yychar+2,yytext()); 
                    return last;
            }
          case 68: break;
          case 29: 
            { last = new Symbol(OR,yychar,yychar+2,yytext()); 
                    return last;
            }
          case 69: break;
          case 30: 
            { last = new Symbol(STRING,yychar,yychar+yytext().length(),
                     new String(yytext().substring(1,yytext().length()-1))); 
   return last;
            }
          case 70: break;
          case 31: 
            { if(--withinComment == 0) yybegin(YYINITIAL);
            }
          case 71: break;
          case 32: 
            { last = new Symbol(QNAME,yychar,yychar+yytext().length(),yytext()); 
   return last;
            }
          case 72: break;
          case 33: 
            { last = new Symbol(DIV,yychar,yychar+3,yytext()); 
                    return last;
            }
          case 73: break;
          case 34: 
            { last = new Symbol(MOD,yychar,yychar+3,yytext()); 
                    return last;
            }
          case 74: break;
          case 35: 
            { last = new Symbol(AND,yychar,yychar+3,yytext()); 
                    return last;
            }
          case 75: break;
          case 36: 
            { last = new Symbol(NODE,yychar,yychar+yytext().length(),yytext()); 
   return last;
            }
          case 76: break;
          case 37: 
            { last = new Symbol(TEXT,yychar,yychar+yytext().length(),yytext()); 
   return last;
            }
          case 77: break;
          case 38: 
            { last = new Symbol(CDATA,yychar,yychar+yytext().length(),yytext()); 
   return last;
            }
          case 78: break;
          case 39: 
            { last = new Symbol(COMMENT,yychar,yychar+yytext().length(),yytext()); 
   return last;
            }
          case 79: break;
          case 40: 
            { last = new Symbol(PI_START,yychar,yychar+yytext().length(),yytext()); 
   return last;
            }
          case 80: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
