/*
 * $Id: terminals.inc,v 1.5 2003/03/20 13:10:55 obecker Exp $
 * 
 * The contents of this file are subject to the Mozilla Public License 
 * Version 1.1 (the "License"); you may not use this file except in 
 * compliance with the License. You may obtain a copy of the License at
 * http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
 * for the specific language governing rights and limitations under the 
 * License.
 *
 * The Original Code is: this file
 *
 * The Initial Developer of the Original Code is Oliver Becker.
 *
 * Portions created by  ______________________ 
 * are Copyright (C) ______ _______________________. 
 * All Rights Reserved.
 *
 * Contributor(s): ______________________________________. 
 */

/* Common terminals for the pattern grammar and the expression grammar */

terminal BAR, SLASH, DSLASH, LBRACK, RBRACK, STAR, COLON;
terminal DOT, DDOT, AT, DOLLAR;
terminal NODE, TEXT, CDATA, PI_START, COMMENT;
terminal PLUS, MINUS, LPAR, RPAR, COMMA;
terminal EQ, NE, LT, LE, GT, GE;
terminal String OR, AND, DIV, MOD;
terminal String QNAME, NCNAME, STRING;
terminal Double NUMBER;
